using ControleFrotas;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
int checks = 0;
void Check(bool valid, string message) { if (!valid) throw new Exception(message); checks++; }
Check(Validation.Plate(" abc-1234 ") == "ABC1234", "Normalização de placa");
Check(Validation.ValidPlate("ABC1234"), "Placa antiga");
Check(Validation.ValidPlate("ABC1D23"), "Placa Mercosul");
Check(!Validation.ValidPlate("ABC12345"), "Placa longa");
Check(!Validation.ValidPlate("123ABCD"), "Placa com ordem inválida");
Check(Validation.ValidCpf("52998224725"), "CPF com dígitos verificadores válidos");
Check(!Validation.ValidCpf("52998224724"), "CPF com dígito inválido");
Check(!Validation.ValidCpf("11111111111"), "CPF repetido");
var vehicle = new VehicleRequest("ABC1D23", "Carro", "Marca", "Modelo", 2024, 12000.125m, true, null);
Check(Validation.VehicleError(vehicle) is null, "Veículo válido");
Check(Validation.VehicleError(vehicle with { Odometer = -1 }) is not null, "Hodômetro negativo");
Check(Validation.VehicleError(vehicle with { Odometer = 1.0001m }) is not null, "Precisão do hodômetro");
Check(Validation.VehicleError(vehicle with { Category = "Inválida" }) is not null, "Categoria inexistente");
Check(Validation.VehicleError(vehicle with { Brand = " " }) is not null, "Marca vazia");
var driver = new DriverRequest("Motorista de teste", "52998224725", "12345678901", "B", new DateOnly(2030, 1, 1), true, null);
Check(Validation.DriverError(driver) is null, "Motorista com formato válido");
Check(Validation.DriverError(driver with { License = "abc" }) is not null, "Formato CNH inválido");
Check(Validation.DriverError(driver with { LicenseCategory = "Z" }) is not null, "Categoria CNH inválida");
var options = new DbContextOptionsBuilder<FleetDb>().UseSqlServer("Server=localhost;Database=ModelCheck;Integrated Security=True;TrustServerCertificate=True").Options;
using var db = new FleetDb(options);
var script = db.Database.GenerateCreateScript();
Check(script.Contains("rowversion"), "Concorrência no esquema SQL");
Check(script.Contains("decimal(12,3)"), "Precisão no esquema SQL");
var context = new DefaultHttpContext { User = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim("company", "1") }, "test")) };
var query = db.Vehicles.Where(x => x.CompanyId == IdentityScope.Company(context)).ToQueryString();
Check(query.Contains("WHERE") && query.Contains("CompanyId"), "Filtro de empresa traduzido para SQL");
Console.WriteLine($"{checks} verificações de regras passaram.");
